### ISSUE TITLE
Export Scanline read, write, and size functions

### ISSUE THREAD

**Issue by JoostvanPinxten** [pearu/pylibtiff#101]
`WriteScanline`, `ReadScanline`, and `ScanlineSize` from the C-library are not exported to the wrapper, is this by design, or is it okay to provide a (very simple) pull-request with these functions added to the wrapper?

It seems these are still supported as API:
https://gitlab.com/libtiff/libtiff/blob/master/libtiff/tif_write.c#L47 
https://gitlab.com/libtiff/libtiff/blob/master/libtiff/tif_read.c#L445 
https://gitlab.com/libtiff/libtiff/blob/master/libtiff/tif_strip.c#L329

**Comment by pearu** [comment]
I am not sure why these functions are missed, its certainly not by design.
A PR would be greatly appreciated.
