### ISSUE TITLE
Big tiff file writes failed

### ISSUE THREAD

**Issue by yasohasakii** [pearu/pylibtiff#112]
Writing a RGB image sizing of 41686*90356 with python3 api `write_image(tiff_img, compression="lzw",write_rgb=True)` ,then I got 
> PredictorEncodeTile: Out of memory

How to solve this?

**Comment by vashineyu** [comment]
Hi yasohasakii,

I met the same issue but resolved by TIFF.open("path_to_saved.tiff", "w8") first and write_tiles into file handler. Hope it works for anyone who met the same issue.
