### ISSUE TITLE
Does work for 1bit compressed TIFF

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pearu/pylibtiff#13]
```
It seems that the library is working well for greyscale and color images, but 
as soon as a pure black&white (1bit/1plan) is given, it fails and renders a 
totally black image

I suppose there is something to do in read_image function cause I saw some 
comments in the code saying "TODO: check for correctness"




```

Original issue reported on code.google.com by `rangoni....@gmail.com` on 11 Mar 2011 at 4:07

**Comment by napter** [comment]
Why is this marked fixed? @pearu indicated that he applied the patch but I don't see it in the code. The current branch still throws the following error when trying to load a 1 bit TIFF image - "NotImplementedError: bits = 1". It's being thrown by get_numpy_type which raises the error if bits % 8 != 0. Does PyLibTiff not support 1 bit images?

**Comment by blokhin** [comment]
Unfortunately, the patch is no more available 😢
Dear @pearu may be you have it somewhere archived?

**Comment by pearu** [comment]
@blokhin the applied patch is in https://github.com/pearu/pylibtiff/commit/8d91479e00593d51debfee1470ca50170e7ac942

**Comment by blokhin** [comment]
@pearu ah but then it doesn't work for me, unfortunately:

```
~# python3 test_tiff.py scanned_bw_multi_page.tif
TIFFReadDirectory: Warning, Unknown field with tag 33579 (0x832b) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 33580 (0x832c) encountered.
Traceback (most recent call last):
  File "test_tiff.py", line 9, in <module>
    image = tif.read_image()
  File "/usr/local/lib/python3.7/dist-packages/libtiff/libtiff_ctypes.py", line 570, in read_image
    typ = self.get_numpy_type(bits, sample_format)
  File "/usr/local/lib/python3.7/dist-packages/libtiff/libtiff_ctypes.py", line 526, in get_numpy_type
    raise NotImplementedError("bits = {0:d}".format(bits))
NotImplementedError: bits = 1
```
Please see the test image [here](https://yadi.sk/i/YS0pjID_fphHwA). May be https://github.com/pearu/pylibtiff/issues/82 is related.
