### ISSUE TITLE
Failed to install pylibtiff using conda-forge

### ISSUE THREAD

**Issue by fr1sky** [pearu/pylibtiff#151]
I'm using
`conda install -c conda-forge pylibtiff`
This command used to work a few years ago, but now it gives:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pylibtiff

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
I'm trying to install on a macOS Monterey 12.3 with M1 chip.
Thanks!!

**Comment by djhoese** [comment]
What version of Python was the environment that you attempted to install this in?

**Comment by fr1sky** [comment]
> What version of Python was the environment that you attempted to install this in?

It's Python 3.10.0.

**Comment by djhoese** [comment]
And your version of `conda` (`conda --version`)?

**Comment by fr1sky** [comment]
> And your version of `conda` (`conda --version`)?

It's conda 23.1.0.

**Comment by djhoese** [comment]
Hm I had thought the arm64 builds were automatic, but it looks like I need to request the migration. Let me see what I can do. FYI in the future it may be better to file these types of issues (conda-forge specific) at the feedstock repository:

https://github.com/conda-forge/pylibtiff-feedstock

**Comment by djhoese** [comment]
Step 1: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4098

**Comment by djhoese** [comment]
Ok so turns out the problems were much bigger than I thought. Try installing the package in an hour (let the package repositories/caches get updated) and the package should be available. Turns out there was a much bigger issue which was that I accidentally renamed the package to `pypylibtiff` a couple months ago so none of our updates were going to conda-forge in any normal way.

**Comment by djhoese** [comment]
Let me know how this goes now. As far as I can tell this should be fixed so I'll close this. If you still have trouble please comment and we can reopen. If someone else has a similar problem please open a new issue.

**Comment by fr1sky** [comment]
> Let me know how this goes now. As far as I can tell this should be fixed so I'll close this. If you still have trouble please comment and we can reopen. If someone else has a similar problem please open a new issue.

It works perfectly right now! Thank you so much for your help. Really appreciate this!!
