### ISSUE TITLE
Cannot be installed with Python3 (even after 2to3 translator)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pearu/pylibtiff#33]
```
What steps will reproduce the problem?

1. direct installation with pip3 or easy_install returns a problem with `print`

2. after translation of the code with `2to3` the problem with `_bitarray.c` 
arises:

    bitarray-0.3.5-numpy/bitarray/_bitarray.c:2520:17: error: ‘PyTypeObject’ has no member named ‘ob_type’
         Bitarraytype.ob_type = &PyType_Type;

```

Original issue reported on code.google.com by `lmet...@gmail.com` on 21 Mar 2015 at 7:57

**Comment by jat255** [comment]
This is still an issue. Most scientific packages are moving to Python 3, so I think it's important that this get resolved. I've taken a shot at in my fork, which I will PR in a second.

**Comment by Padoup-Padoup** [comment]
Hi, 
I am also facing compilation issues with Python 3, and a working version of pylibtiff with Python3 would be of great help.

What I did:
- run `2to3`
- correct remaining errors by replacing `
Bitarraytype.ob_type = &PyType_Type;` by `Py_TYPE(&Bitarraytype) = &PyType_Type;`.
- Initialized `Py_TPFLAGS_HAVE_WEAKREFS` to 0 in `_bitarray.c`:

```{c}
#if PY_MAJOR_VERSION >=3
#  define Py_TPFLAGS_HAVE_WEAKREFS 0
#endif
```
With this modifications, I achieved to get a compiled version (with a lot of warnings, though).
When importing with Python3, there was also a problem when parsing the version number (don't know why). I simply commented the lines in `libtiff_ctypes.py` and replaced them with `libtiff_version = '4.0.3'`. After a little bit of chmod in the compiled files, I ran into: 

```{python}
ImportError: No module named 'tif_lzw'
```

As far as I understand, the `tif_lzw` module has not been built during the compilation process. Any thought on how to solve that?

Thank you!

**Comment by Padoup-Padoup** [comment]
Thanks a lot, it works!
