### ISSUE TITLE
Save incorrectly the image read

### ISSUE THREAD

**Issue by cedricpinson** [pearu/pylibtiff#39]
I am not able to save a tiff image rgba float32 correctly
Looks like an array order:

```
from libtiff import TIFF, TIFFimage

    tif = TIFF.open("test3.tif", mode='r')
    image_read = tif.read_image()
    print image_read.shape
    image_save = TIFFimage(image_read)
    image_save.write_file("out.tif")
```

```
iinfo -v out.tif
out.tif :    4 x 1024, 1 channel, float tiff
1024 subimages
```

the image to test is a 10x10x4 float32 (rgba) file
https://infinit.io/_/KCdNUuH

**Comment by pearu** [comment]
The test image is not available. Please reopen the issue and provide the tif file that reproduces this issue.
