### ISSUE TITLE
I get a array by reading a tiff iamge, but the array's value is all empty.

### ISSUE THREAD

**Issue by John1911603424** [pearu/pylibtiff#54]
This is the code:

from libtiff import TIFF
# to open a tiff file for reading:
tif = TIFF.open('013022223103.tif', mode='r')#('013022223103.tif', mode='r')
# to read an image in the currect TIFF directory and return it as numpy array:
image = tif.read_image()

**Comment by pearu** [comment]
Please reopen this issue with provided example tiff file that reproduces the issue.
