### ISSUE TITLE
not able to install libtiff on linux

### ISSUE THREAD

**Issue by Borda** [pearu/pylibtiff#55]
I ve just wanted to install the libtiff but not able to run it or even import.
I used `pip install libtiff` to get latest version which which run fine but later on calling `import libtiff` crash... I found I have libtiff5 on my computer so I compiled and installed libtiff-4.0.6 from source and uninstall libtift and installed again, but it does not help...

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libtiff
Generating '/usr/local/lib/python2.7/dist-packages/libtiff/tiff_h_4_0_6.py'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/libtiff/__init__.py", line 20, in <module>
    from .libtiff_ctypes import libtiff, TIFF, TIFF3D
  File "/usr/local/lib/python2.7/dist-packages/libtiff/libtiff_ctypes.py", line 102, in <module>
    f = open(fn, 'w')
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/libtiff/tiff_h_4_0_6.py'
```

In the end it `/usr/local/lib/python2.7/dist-packages/libtiff/tiff_h_4_0_6.py` does not exits

**Comment by pearu** [comment]
When first imported, libtiff is trying to generate tiff_x_y_z.py file but in your cases it does not have permissions to write the file to desired location. In case you have superuser privileges, try running
`
sudo python -c 'import libtiff'
`
that should generate the file. Afterwards, you should be able to import libtiff without problems.

**Comment by Borda** [comment]
btw, why the file `tiff_h_4_0_6.py` is not created during installation but with first import instead... 
I tried `sudo pip ...` but it would never cross my mind to use the `sudo python ...`

**Comment by pearu** [comment]
I agree that the current situation can be improved.

Since importing from `sudo pip...` might have other implications, I am thinking of catching the IOError, give a warning and `sudo python ...` suggestion, and let libtiff continue with generated data (that will then be generated each time libtiff is imported until the file gets created in one or another way).
