### ISSUE TITLE
Incorrect link on PyPi

### ISSUE THREAD

**Issue by MaximeMaW** [pearu/pylibtiff#64]
Hi,

This is just to let you know that the PyPi page of libtiff (https://pypi.python.org/pypi/libtiff/0.4.0) references to a non-existing repository, namely:  http://pylibtiff.googlecode.com

**Comment by pearu** [comment]
The link must be updated in setup.py file.

**Comment by pearu** [comment]
The reference will be fixed when new libtiff is released to pypi.
