### ISSUE TITLE
New version of libtiff: 4.0.9

### ISSUE THREAD

**Issue by dirkboye** [pearu/pylibtiff#71]
There was a new version of libtiff released. Following file is needed:
libtiff/tiff_h_4_0_9.py

In current Fedora pip install libtiff will result in a broken pylibtiff.

**Comment by pearu** [comment]
When you import libtiff as superuser, the missing file will be generated. Please send or upload the generated file so that it could be added to the pylibtiff repo.

**Comment by dirkboye** [comment]
#72 Thanks for merging the pull request. A copy was sufficient. I tested if there's any difference between tiff_h_4_0_9.py and tiff_h_4_0_8.py when using an import as superuser:

`[dirk@localhost libtiff]$ sudo ipython
Python 3.6.3 (default, Oct  9 2017, 12:11:29) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import libtiff
Generating '/usr/lib64/python3.6/site-packages/libtiff/tiff_h_4_0_9.py' from '/usr/include/tiff.h'

In [2]: exit
[dirk@localhost libtiff]$ diff /usr/lib64/python3.6/site-packages/libtiff/tiff_h_4_0_9.py /usr/lib64/python3.6/site-packages/libtiff/tiff_h_4_0_8.py
`

Thanks for already releasing a 0.4.2 to pypi!

**Comment by pearu** [comment]
A new release has been made with the missing file included, thanks to Dirk Boye!.
