### ISSUE TITLE
Is it possible to open tiff file from numpy array?

### ISSUE THREAD

**Issue by Omnipresent** [pearu/pylibtiff#74]
I have a tiff file that is represented as a numpy array. Is it possible to use pylibtiff to open this file? I see that he `open` method only takes an actual file name but wanted to know if same is possible for a numpy array ?

**Comment by pearu** [comment]
Tiff file has a specific structure that contains image data and its metadata. Could you provide an example of the corresponding numpy array that represents a tiff file? I cannot figure out how such a representation would be possible...
