### ISSUE TITLE
Unittest failures on i386 and bigendian arch

### ISSUE THREAD

**Issue by avalentino** [pearu/pylibtiff#86]
We are trying to build a debian package for pylibtiff (https://tracker.debian.org/pkg/pylibtiff).
We found some issue during unit testing on different architectures:

* i386: https://buildd.debian.org/status/fetch.php?pkg=pylibtiff&arch=i386&ver=0.4.2-1&stamp=1545821993&raw=0
* ppc64: https://buildd.debian.org/status/fetch.php?pkg=pylibtiff&arch=ppc64&ver=0.4.2-1&stamp=1545822045&raw=0
* powerpc: https://buildd.debian.org/status/fetch.php?pkg=pylibtiff&arch=powerpc&ver=0.4.2-1&stamp=1545822914&raw=0
* mips: https://buildd.debian.org/status/fetch.php?pkg=pylibtiff&arch=mips&ver=0.4.2-1&stamp=1545820221&raw=0
* mipsel: https://buildd.debian.org/status/fetch.php?pkg=pylibtiff&arch=mipsel&ver=0.4.2-1&stamp=1545826070&raw=0
* s390x: https://buildd.debian.org/status/fetch.php?pkg=pylibtiff&arch=s390x&ver=0.4.2-1&stamp=1545973100&raw=0

Please note that ppc64, powerpc, mips and s390x are bigendian architectures if I'm not wrong.

I gave a quick look to the code and it seems to me that it should work at least on i386.

Can you please provide some hint?

**Comment by pearu** [comment]
I agree that some of these errors are related to endianness as bittools assumes little endianess. This needs to be fixed.

The `test_wordbits` failure is related to the fact that the corresponding systems (e.g. i386) are 32-bit but the test assumed 64-bit system. The test is now fixed in the github repo.

**Comment by avalentino** [comment]
Dear @pearu thank you for the feedback.

Just FYI currently in debian the bittools extension has been disabled in favour of the bitarray backend.
This seems to fix all build failures.

Do you think that the solution makes sense?
Is bitarray shower than bittools?

**Comment by pearu** [comment]
Actually, bitarray or bittools is used only in lzw.py that is now deprecated in favor of much more efficient tif_lzw extension module. So, I think the solution in debian is quite fine.

I think someday I'll move bittools to a separate project and bitarray can be dropped altogether (as it is maintained elsewhere): issue #95 .
